---
title: "Narrate Echarts Plots"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Narrate Echarts Plots}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>"
)
```

```{r setup}
library(narrator)
library(dplyr)
library(purrr)
library(echarts4r)
```



```{r}
barplot <- sales %>%
  dplyr::group_by(Region) %>%
  dplyr::summarise(Sales = sum(Sales)) %>%
  echarts4r::e_chart(Region) %>%
  echarts4r::e_bar(Sales) %>%
  echarts4r::e_tooltip()

barplot
```


```{r}
bar_narrative <- barplot %>%
  echarts4r::e_get_data() %>%
  purrr::map_df(bind_rows) %>%
  narrate_descriptive()

bar_narrative
```

```{r}
bar_narrative <- bar_narrative %>%
  unlist(use.names = FALSE) %>%
  paste("\n", collapse = "") 

barplot %>%
  echarts4r::e_text_g(
    style = list(
      text = bar_narrative,
      fontSize = 16
    ),
    left = "2%",
    top = "3%",
    rotation = 0
  )
```


```{r}
scatterplot <- sales %>%
  dplyr::group_by(Region, Product) %>%
  dplyr::summarise(Sales = sum(Sales),
            Quantity = sum(Quantity),
            Price = mean(Price), .groups = "keep") %>%
  echarts4r::e_chart(Sales) %>%
  echarts4r::e_scatter(Quantity, Price) %>%
  echarts4r::e_tooltip()

scatterplot
```

```{r}
scatterplot %>%
  echarts4r::e_get_data() %>%
  purrr::map_df(bind_rows) %>%
  narrate_descriptive()
```


```{r}
piechart <- sales %>%
  dplyr::group_by(Product) %>%
  dplyr::summarise(Sales = sum(Sales)) %>%
  echarts4r::e_chart(Product) %>%
  echarts4r::e_pie(Sales) %>%
  echarts4r::e_tooltip()

piechart
```

```{r}
piechart %>%
  echarts4r::e_get_data() %>%
  purrr::map_df(bind_rows) %>%
  narrate_descriptive()
```
