---
title: "Formatting Output"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Formatting Output}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>"
)
```

```{r setup}
library(narrator)
library(dplyr)
library(htmltools)
```

You can use the output of `narrator` in HTML reports or shiny with additional formatting that can be added using `format_pct()` and `add_tag()` functions. If the output is a named list, which is a default behaviour of the `narrate_*` functions, names can be used as headers and narratives rendered below.

```{r}
narrative <- sales %>%
  group_by(Region, Product) %>%
  summarise(Sales = sum(Sales, na.rm = TRUE)) %>%
  arrange(desc(Sales)) %>%
  narrate_descriptive() %>%
  format_pct()

names(narrative) <- add_tag(names(narrative), "h3")

narrative <- unlist(narrative)

mapply(c, names(narrative), as.character(narrative)) %>%
  as.character() %>%
  htmltools::HTML()
```


```{r}

```


```{r}

```


```{r}

```
