---
title: "Python"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Python}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>"
)
```


Basic narrative type is descriptive stats, looking into outliers or biggest contributors to the total volumes in the data set. This narratives are quite useful and can help to look deeper into the data set hierarchy.

```{r setup, include=FALSE}
library(narrator)
library(reticulate)

if (!virtualenv_exists("r-reticulate")) reticulate::virtualenv_create("r-reticulate")
python <- "~/.virtualenvs/narrator/bin/python"
reticulate::use_virtualenv("r-reticulate")

reticulate::virtualenv_install(envname = "r-reticulate", packages = "pynarrator")
py_install("pynarrator")

sales <- narrator::sales
```

## Installation

To use the Python version of the package install `pynarrator` from pip:

```{bash include=FALSE}
pip3 install pynarrator
```

```{bash eval=FALSE}
pip3 install pynarrator
```


```{python}
import os
from pynarrator import narrate_descriptive, read_data
import pprint
```

```{python eval=FALSE}
sales = read_data()
```

```{python include=FALSE}
sales = r.sales
```

```{python}
narrative = narrate_descriptive(
  df = sales, 
  measure = 'Sales', 
  dimensions = ['Region', 'Product'], 
  return_data = False, 
  coverage = 0.5
  )
  
pprint.pprint(narrative)
```

```{python}
df_two = (sales
          .query('Region in ["NA", "EMEA"]')
          .groupby(['Region', 'Product'])
          .agg(Sales=('Sales', 'sum'))
          .reset_index()
          .sort_values('Sales', ascending=False)
         )

pprint.pprint(df_two)
```

```{python}
narrative = narrate_descriptive(df_two)
pprint.pprint(narrative)
```

```{python}
narrative = narrate_descriptive(df_two, simplify = True)
pprint.pprint(narrative)
```
